config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  get 'courses/show'

  get 'courses/new'

  resources :schools do
    resources :teachers
    resources :students
    resources :courses
  end

   root 'home#dashboard'

end

app/models/concentration.rb
class Concentration < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :course

  validates :teacher_id, uniqueness: {
    scope: :course_id,
    message: "Teacher can only sign up for a course once"
  }
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :school
  has_many :concentrations
  has_many :enrollments

  validates :name, presence: true
  validates :description, presence: true
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student
  belongs_to :course


  validates :student_id, uniqueness: {
    scope: :course_id,
    message: "Student can only sign up for a course once"
  }

  def student_name
    student.name
  end

  def course_name
    course.name
  end
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :teachers
  has_many :students
  has_many :courses

  validates :name, presence: true
  validates :motto, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :school, counter_cache: true
  has_many :enrollments
  has_many :courses, through: :enrollments
  has_many :teachers, through: :courses, source: :concentrations


  validates :name, presence: true
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :school
  has_many :concentrations
  has_many :courses, through: :concentrations
  has_many :students, through: :courses, source: :enrollments

  validates :name, presence: true

  def school_id
    school.id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @school = get_school
    @courses = @school.courses.page params[:page]
  end

  def show
    @school = get_school
    @course = get_course
  end

  def new
    @school = get_school
    @course = Course.new
  end

  def create
    @school = get_school
    @course = @school.courses.build(course_params)
    if @course.save
      redirect_to school_courses_path
    else
      render :new
    end
  end

  def edit
    @school = get_school
    @course = get_course
  end

  def update
    @school = get_school
    @course = get_course
    if @course.update(course_params)
      redirect_to school_course_path(@school, @course)
    else
      render :edit
    end
  end

  def destroy
    @course = get_course
    if @course.destroy
      redirect_to school_courses_path
    else
      redirect_to (:back)
    end
    rescue ActiveRecord::InvalidForeignKey
      redirect_to (:back)

  end

  private

  def get_school
    School.find(params.fetch(:school_id))
  end

  def get_course
    Course.find(params.fetch(:id))
  end
  def course_params
    params.require(:course).permit(:name, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
    @last_student = Student.last
    @top_schools = School.order(students_count: :desc).limit(10)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all.page params[:page]
  end

  def show
    @school = get_school_by_id
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)
    if @school.save
      redirect_to school_path(@school.id)
    else
      render :new
    end
  end

  def edit
    @school = get_school_by_id
  end

  def update
    @school = get_school_by_id
    if @school.update(school_params)
      redirect_to school_path(@school.id)
    else
      render :edit
    end
  end

  def destroy
    @school = get_school_by_id
    if @school.destroy
      redirect_to schools_path
    else
      redirect_to (:back)
    end
  end

  private
  def school_params
    params.require(:school).permit(:name, :motto)
  end

  def get_school_by_id
    School.find(params.fetch(:id))
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @school = get_school
    @students = @school.students.page params[:page]
  end

  def show
    @school = get_school
    @student = get_student
  end

  def new
    @school = get_school
    @student = Student.new
  end

  def create
    @school = get_school
    @student = @school.students.build(student_params)
    if @student.save
      redirect_to school_students_path
    else
      render :new
    end
  end

  def edit
    @school = get_school
    @student = get_student
  end

  def update
    @school = get_school
    @student = get_student
    if @student.update(student_params)
      redirect_to school_student_path(@school, @student)
    else
      render :edit
    end
  end

  def destroy
    @student = get_student
    if @student.destroy
      redirect_to school_students_path
    else
      redirect_to (:back)
    end
  end

  private

  def get_school
    School.find(params.fetch(:school_id))
  end

  def get_student
    Student.find(params.fetch(:id))
  end
  def student_params
    params.require(:student).permit(:name)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @school = get_school
    @teachers = @school.teachers.page params[:page]
  end

  def show
    @school = get_school
    @teacher = get_teacher
    @enrollments = @teacher.students
  end

  def new
    @school = get_school
    @courses = @school.courses
    @teacher = Teacher.new
  end

  def create
    binding.pry
    @school = get_school
    @teacher = @school.teachers.build(teacher_params)
    if @teacher.save
      redirect_to school_teachers_path
    else
      render :new
    end
  end

  def edit
    @school = get_school
    @teacher = get_teacher
  end

  def update
    @school = get_school
    @teacher = get_teacher
    if @teacher.update(teacher_params)
      redirect_to school_teacher_path(@school, @teacher)
    else
      render :edit
    end
  end

  def destroy
    @teacher = get_teacher
    if @teacher.destroy
      redirect_to school_teachers_path
    else
      redirect_to (:back)
    end
  end

  private

  def get_school
    School.find(params.fetch(:school_id))
  end

  def get_teacher
    Teacher.find(params.fetch(:id))
  end
  def teacher_params
    params.require(:teacher).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/courses/_coursebox.html.erb
<h3><%= link_to course.name,
        school_course_path(school_id: course.school_id,
                                   id: course.id) %></h3>

app/views/courses/_form.html.erb
<% if @course.errors.any? %>
  <section>
    <ul>
      <% @course.errors.full_messages.each do |err| %>
        <li>
          <%= err %>
        </li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for([@school, @course]) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.submit class: "blue darken-2 waves-effect waves-light btn" %>
<% end %>

app/views/courses/edit.html.erb
<h1>courses#edit</h1>
<%= render partial: "form" %>

app/views/courses/index.html.erb
<h1>courses#index</h1>
<p>Find me in app/views/courses/index.html.erb</p>
<%= link_to "Add course", new_school_course_path, class:"right blue darken-2 waves-effect waves-light btn" %>
<%= render partial: 'schools/schoolbox', locals: { school: @school } %>
<% @courses.each do |course| %>
  <%= render partial: 'coursebox', locals: { course: course } %>
<% end %>
<%= paginate @courses %>

app/views/courses/new.html.erb
<h1>courses#new</h1>
<p>Find me in app/views/courses/new.html.erb</p>

<%= render partial: "form" %>

app/views/courses/show.html.erb
<h1><%= link_to "courses", school_courses_path(@school.id) %></h1>

<p>Find me in app/views/courses/show.html.erb</p>
<div class="row">
  <%= link_to "Delete", school_course_path(school_id: @course.school_id,
              id: @course.id), method: "DELETE",
              class: "delete-edit-button right red waves-effect waves-light btn",
              data: { confirm: "Are you sure you want to delete this School?" }%>

    <%= link_to "Edit", edit_school_course_path(school_id: @course.school_id,
                               id: @course.id),
                class: "delete-edit-button right orange waves-effect waves-light btn"%>

  <div class="col s12 m8 l10">
      <h3> <%= @course.name %> </h3>
      <p> <%= @course.description %></p>
    </div>
</div>

app/views/home/dashboard.html.erb
<div class="row">
<h2> Newest Student </h2>
<%= render partial: '/students/studentbox', locals:{ student:@last_student } %>
</div>
<h2> Top 10 Schools <small> by student count </small></h2>
<div class="row">
<% @top_schools.each do |school| %>
<%= render partial: '/schools/schoolbox', locals:{ school:school }%>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecureSchool</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <ul class="container">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Schools", schools_path %></li>
  </ul>
</nav>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/schools/_form.html.erb
<% if @school.errors.any? %>
  <section>
    <ul>
      <% @school.errors.full_messages.each do |err| %>
        <li>
          <%= err %>
        </li>
      <% end %>
    </ul>
  </section>
<% end %>
<%= form_for(@school) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :motto %>
<%= f.text_field :motto %>
<%= f.submit "Create School", class: "blue darken-2 waves-effect waves-light btn" %>
<% end %>

app/views/schools/_schoolbox.html.erb
<div class="row">
  <div class="col s12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= link_to school.name, school_path(school.id) %></span>
        <p><%= school.motto %></p>
        <div class="card-action">
        <%=link_to "Teachers: #{school.teachers.count}", school_teachers_path(school.id) %>
        <%= link_to "Students: #{school.students.count}", school_students_path(school.id) %>
        <%= link_to "Courses: #{school.courses.count}", school_courses_path(school.id) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/schools/edit.html.erb
<h1>Schools#edit</h1>
<p>Find me in app/views/schools/edit.html.erb</p>

<%= render partial: "form" %>

app/views/schools/index.html.erb
<h1>Schools#index</h1>
<p>Find me in app/views/schools/index.html.erb</p>
<%= link_to "Create New School", new_school_path, class:"right blue darken-2 waves-effect waves-light btn" %>

<% @schools.each do |school| %>
<%= render partial: "schoolbox",
            locals: { school: school }%>

<% end %>
<%= paginate @schools %>

app/views/schools/new.html.erb
<h1>Schools#new</h1>
<p>Find me in app/views/schools/new.html.erb</p>

<%= render partial: "form" %>

app/views/schools/show.html.erb
<h1>Schools#show</h1>


<div class="row">
  <%= link_to "Delete", school_path(@school.id), method: "DELETE",
              class: "delete-edit-button right red waves-effect waves-light btn",
              data: { confirm: "Are you sure you want to delete this School?" }%>

    <%= link_to "Edit", edit_school_path(@school.id),
                class: "delete-edit-button right orange waves-effect waves-light btn"%>


    <%= render partial: 'schoolbox', locals: { school: @school } %>
  

</div>

app/views/students/_form.html.erb
<% if @student.errors.any? %>
  <section>
    <ul>
      <% @student.errors.full_messages.each do |err| %>
        <li>
          <%= err %>
        </li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for([@school, @student]) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit class: "blue darken-2 waves-effect waves-light btn" %>
<% end %>

app/views/students/_studentbox.html.erb
<div class="col s12">
 <div class="card green darken-4">
   <div class="student-card card-content white-text">
     <span class="card-title"><%= link_to student.name, school_student_path(school_id: student.school_id,
                                id: student.id) %></span>

      <p> <%= student.school.name %> </p>

      <div class="card-action">
        Courses:
          <div class="row">
            <% student.courses.each do |course| %>

            <div class="col s12 m6 l4"><%= course.name %> </div>
            <% end %>
          </div>
      </div>
   </div>
 </div>
</div>

app/views/students/edit.html.erb
<h1>students#edit</h1>
<%= render partial: "form" %>

app/views/students/index.html.erb
<h1>students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>
<%= link_to "Add Student", new_school_student_path, class:"right blue darken-2 waves-effect waves-light btn" %>
<%= render partial: 'schools/schoolbox', locals: { school: @school } %>

<div class="row">
<% @students.each do |student| %>
  <%= render partial: 'studentbox', locals: { student: student } %>
<% end %>
</div>
<%= paginate @students %>

app/views/students/new.html.erb
<h1>students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

<%= render partial: "form" %>

app/views/students/show.html.erb
<h1><%= link_to "students", school_students_path(@school.id) %></h1>

<p>Find me in app/views/students/show.html.erb</p>
<div class="row">
  <%= link_to "Delete", school_student_path(school_id: @student.school_id,
              id: @student.id), method: "DELETE",
              class: "delete-edit-button right red waves-effect waves-light btn",
              data: { confirm: "Are you sure you want to delete this School?" }%>

    <%= link_to "Edit", edit_school_student_path(school_id: @student.school_id,
                               id: @student.id),
                class: "delete-edit-button right orange waves-effect waves-light btn"%>

  <div class="col s12 m8 l10">
      <h3> <%= @student.name %> </h3>
    </div>
</div>

app/views/teachers/_form.html.erb
<% if @teacher.errors.any? %>
  <section>
    <ul>
      <% @teacher.errors.full_messages.each do |err| %>
        <li>
          <%= err %>
        </li>
      <% end %>
    </ul>
  </section>
<% end %>


<%= form_for([@school, @teacher]) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.submit class: "blue darken-2 waves-effect waves-light btn" %>
<% end %>

app/views/teachers/_teacherbox.html.erb
  <div class="col s6">
   <div class="card blue-grey darken-2">
     <div class="card-content white-text">
       <span class="card-title"><%= link_to teacher.name, school_teacher_path(school_id: teacher.school_id,
                                  id: teacher.id) %></span>

        <p> <%= teacher.school.name %> </p>
        <% teacher.courses.each do |course| %>
        <p> <%= course.name %> </p>
        <% end %>
       <div class="card-action">
       </div>
     </div>
   </div>
  </div>

app/views/teachers/edit.html.erb
<h1>Teachers#edit</h1>
<%= render partial: "form" %>

app/views/teachers/index.html.erb
<h1>Teachers#index</h1>
<p>Find me in app/views/teachers/index.html.erb</p>
<%= link_to "Add Teacher", new_school_teacher_path, class:"right blue darken-2 waves-effect waves-light btn" %>
<%= render partial: 'schools/schoolbox', locals: { school: @school } %>

<div class="row">
<% @teachers.each do |teacher| %>
  <%= render partial: 'teacherbox', locals: { teacher: teacher } %>
<% end %>
</div>
<%= paginate @teachers %>

app/views/teachers/new.html.erb
<h1>Teachers#new</h1>
<p>Find me in app/views/teachers/new.html.erb</p>

<%= render partial: "form" %>

app/views/teachers/show.html.erb
<h1><%= link_to "Teachers", school_teachers_path(@school.id) %></h1>

<p>Find me in app/views/teachers/show.html.erb</p>
<div class="row">
  <%= link_to "Delete", school_teacher_path(school_id: @teacher.school_id,
              id: @teacher.id), method: "DELETE",
              class: "delete-edit-button right red waves-effect waves-light btn",
              data: { confirm: "Are you sure you want to delete this School?" }%>

    <%= link_to "Edit", edit_school_teacher_path(school_id: @teacher.school_id,
                               id: @teacher.id),
                class: "delete-edit-button right orange waves-effect waves-light btn"%>

  <div class="col s12 m8 l10">
      <h3> <%= @teacher.name %> </h3>
    </div>
</div>

<% @enrollments.each do |enrollment| %>
<p><%= enrollment.student_name %> | <%= enrollment.course_name %></p>
<% end %>